### ISSUE TITLE
BUG: Hovering Over Audio Track Element Causes Glitch on MUSIC Section

### ISSUE THREAD

**Issue by Nina-Tru** [naumch1k/one-fall#18]
### Description
When hovering a cursor over the boundary of the audio track element on the MUSIC section, the right edge of the element jitters, causing the Play button to overlap with the track number. These two images flicker, rapidly alternating between each other.

### Environment
Chrome v. 126.0.6478.127
 
### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/#music
2. Locate any interactive audio track button.
3. Slowly move the mouse cursor to the boundary of the button, especially around the right edge.

### Actual result:
The right edge of the element jitters, causing the Play button to overlap with the track number. This results in a flickering effect as the images rapidly alternate.

### Expected result:
The element should remain stable, and the Play button should not overlap with the track number. There should be no flickering.

### Attachments:

https://github.com/naumch1k/one-fall/assets/128139810/4eaf8745-0712-4948-bfc5-7b8b8b11ea02

**Comment by naumch1k** [comment]
Hey @Nina-Tru, please remember to set the **Severity** for new bug reports. Thanks!

![Image](https://github.com/user-attachments/assets/82539460-f366-44ac-8801-a35c109339d0)
