### ISSUE TITLE
BUG: The Audio Track is Paused after Switching to Another Track

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#25]
### Description
The audio track continues playing from the point it was interrupted after switching to another track and replaying it again.

### Environment
 **Desktop**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 127.0.6533.89

### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/
2. Click on **MUSIC** link in the main navigation menu.
3. Click on any track for playing.
4. Click on another track for playing.
5. Click on the first track that was played previously.

### Actual result:
The audio track is paused after switching to another track.

### Expected result:
The audio track is stopped after switching to another track. It starts playing from the beginning after switching to another track.

### Attachments:

https://github.com/user-attachments/assets/6d12c8e4-d743-406d-9514-a3af6c1a565b

### Additional context
This issue affects all tracks on the site and also occurs in the following environments:

- Firefox version 128.0.3

- Microsoft Edge version 127.0.2651.86

- Android 10, Google Chrome version 122.0.6261.119

- iPadOS 17.6, Safari version 17.6

**Comment by naumch1k** [comment]
Hey @yuliia-harshyna , please remember to set the **Severity** for new bug reports. Thanks!

![Image](https://github.com/user-attachments/assets/25233ab5-58a9-4284-b02f-3f3da769dc4c)

**Comment by naumch1k** [comment]
.take
