### ISSUE TITLE
BUG: Image in the Merch Section is Highlighted in Blue after Tapping

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#27]
### Description
In the merchandise section, tapping on an image causes it to be highlighted in blue.

### Environment
**Smartphone:**
- Device: Motorola e7 power
- OS:  Android 10
- Browser: Google Chrome
- Version: 122.0.6261.119

### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/
2. Tap on the **MENU** button.
3. Tap on the **MERCH** menu item.
4. Tap on the first merch image.

### Actual result:
Image in the merch section is highlighted in blue after tapping on it.

### Expected result:
Image remains unchanged in the merch section after tapping. 

### Attachments:

https://github.com/user-attachments/assets/c164f92c-c082-469c-ae7b-6fe7ab3a4878

### Additional context
This issue occurs for all images in the merch section.

**Comment by ghost** [comment]
@naumch1k  Hello! I found this issue was fixed after adding a carousel controls to the merch section.

**Comment by naumch1k** [comment]
> [@naumch1k](https://github.com/naumch1k) Hello! I found this issue was fixed after adding a carousel controls to the merch section.

Hey @yuliia-harshyna, thanks for the update! I'll look into it since this specific issue wasn't something I addressed or fixed while implementing the carousel.
