### ISSUE TITLE
FEATURE: Add a Visual Highlight to the Navigation Links in the Overlay Menu to Indicate User's Current Location

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#28]
### Is your feature request related to a problem? Please describe.
The current design lacks a visual indicator for the user's current location within the overlay navigation menu on tablets and mobile devices. Highlighting the active menu item offers several key advantages:

- **Improved Navigation:** Highlighting the current navigation link helps users easily orient themselves on the site by showing which section they are in at the moment. This significantly simplifies navigation.

- **Increased Usability:** Indicating the active menu makes interaction with the site more intuitive. Users can quickly understand where they are without needing to search for additional visual clues or read text.

### Describe the solution you'd like
Menu items can be highlighted using another color, using graphic elements, or another font size.

### Attachments

![MOBILE_MENU](https://github.com/user-attachments/assets/d82c9bb3-9f10-4b90-acf8-c0de7435c0f1)
![TABLET_MENU](https://github.com/user-attachments/assets/1c3120c0-be30-4c3f-b421-939011fb0019)

**Comment by Nina-Tru** [comment]
### Main Navigation Menu Issue: No Section Highlighting When Scrolling Upwards

Main Navigation Menu currently functions only from top to bottom. When scrolling down the page, the section name appears at the top, providing a clear visual indication of the current section the user is in. 

However, when navigating upwards (bottom to top), the section names remain aligned at the same level and do not change color to highlight the section being viewed. This can cause confusion for users as they are unable to easily identify their current section when scrolling upwards.

**Comment by naumch1k** [comment]
> However, when navigating upwards (bottom to top), the section names remain aligned at the same level and do not change color to highlight the section being viewed. This can cause confusion for users as they are unable to easily identify their current section when scrolling upwards.

Hey @Nina-Tru 👋 Thanks for pointing out this extra issue! Could you share some screenshots or a video to help illustrate the problem? It’ll make it easier for everyone to understand what’s happening.

![Image](https://github.com/user-attachments/assets/9cb69a40-2696-4490-8e6f-6e86b0cb9667)



![Image](https://github.com/user-attachments/assets/4b9a62ba-260e-45b8-b37d-4e691328656b)

**Comment by naumch1k** [comment]
.take
