### ISSUE TITLE
BUG: The 'Bandcamp’ Icon is Missing in the Social Links Sidebar After Screen Rotation

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#33]
### Description
The 'Bandcamp’ icon is missing in the social links sidebar after screen rotation from portrait to landscape. It is still active, just only not visible. After tapping on the invisible 'Bandcamp’ icon it becomes visible again.

### Environment

**Tablet**
- Device: iPad (9th generation)
- OS: iPadOS 17.6
- Browser: Safari
- Version: 17.6

### Preconditions:
1. Tablet is in portrait orientation.

### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/
2. Change the orientation of the tablet to landscape.
3. Pay attention to the social links sidebar.

### Actual result:
The 'Bandcamp’ icon is missing in the social links sidebar after screen rotation from portrait to landscape.

### Expected result:
The 'Bandcamp’ icon remains visible after screen rotation from portrait to landscape.

### Attachments:
![XRecorder_Edited_11082024_141134](https://github.com/user-attachments/assets/94db208d-be8d-4575-a7a2-ba21c5b85a52)

https://github.com/user-attachments/assets/59c95f95-38a2-42ce-9d65-e83b52b529e5

### Additional context
This issue also occurs in Google Chrome browser, version 127.0.6533.107.
Also the 'Bandcamp’ is missing after tapping on the ‘Youtube’ icon in the social links sidebar.
The 'Bandcamp’ icon remains visible after screen rotation, if the overlay menu is left open in portrait orientation.

https://github.com/user-attachments/assets/99978969-de63-452b-9764-4b571d85245d

**Comment by naumch1k** [comment]
.take
