### ISSUE TITLE
BUG: Focus Styles Are Applied to the ‘READ MORE’ Link in the ‘ABOUT’ Section After Clicking

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#38]
### Description
After clicking the just visited link retains focus styles. These styles applied only to the last visited link. To deselect the link you need to click elsewhere.
This behavior is caused by the keyboard accessibility feature. In this case those styles indicate the focus of the current element when using the keyboard.

### Environment
**Desktop**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 127.0.6533.100

### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/
2. Click on the **'ABOUT’** main menu item.
3. Scroll down to the second part of the **'ABOUT’** section (About story).
4. Click on the **'READ MORE ➞’** link (page opens in new tab).
5. Go back to the site.

### Actual result:
Focus styles are applied to the ‘READ MORE’ link in the ‘ABOUT’ section after clicking.

### Expected result:
Default link styles are applied to the ‘READ MORE’ link in the ‘ABOUT’ section after clicking.

### Attachments:
https://github.com/user-attachments/assets/5495f839-e50b-43da-afac-8bb9b2646eb7

### Additional context
This issue occurs to the following links:
- 'BUY DIGITAL ALBUM' (music section);
- 'BUY ON BANDCAMP ➞' (for each product card in the merch section);
- 'READ ON... ➞' (for each article in the press section).

This issue doesn't occur to the social links and links in the footer.

**Comment by naumch1k** [comment]
.take
