### ISSUE TITLE
BUG: The Rounded Corners of the 'Name' Field of the 'MESSAGE US' Form Are Displayed

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#39]
### Description
The outlines of the border corners (upper and bottom) of the 'Name' field are displayed. Also, when zooming in, a thin line of the upper border is displayed.

### Environment
**Tablet**
 - OS: iPadOS 17.6
 - Browser: Safari
 - Version: 17.6

### Steps to reproduce:
1. Go to https://develop--one-fall.netlify.app/
2. Scroll down to the footer of the site.

### Actual result:
The rounded corners of the 'Name' field of the 'MESSAGE US' form are displayed.

### Expected result:
Only the bottom border of the 'Name' field of the 'MESSAGE US' form is displayed.

### Attachments:
![border_3](https://github.com/user-attachments/assets/b621e13b-b57c-4714-81a5-73551ddf6c2a)

### Additional context
This issue happens only on tablet. Also it happens with the 'Email' field of the 'MESSAGE US' form and in the Google Chrome version 127.0.6533.107.
Displaying the upper border after zooming in:
![border_2](https://github.com/user-attachments/assets/f3182720-8297-43c6-8638-9b9ca7b0100a)

**Comment by Yura33-dev** [comment]
.take
