### ISSUE TITLE
FEATURE: Highlight the Paused Audio Track

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#43]
### Is your feature request related to a problem? Please describe.
When audio track is paused it is not highlighted. Therefore, the user might be confused about which song was playing.

### Describe the solution you'd like
Switch the 'Equalizer' icon to the 'Play' icon and keep highlighting the paused track.

### Additional context
![paused_track](https://github.com/user-attachments/assets/040fa593-e02a-41fb-beb3-53eae034e97d)

**Comment by naumch1k** [comment]
.take
