### ISSUE TITLE
BUG: The Vertical Scrolling is Absent in the Input Field 'Your message' of the 'Message us' Form After Entering Eight Lines 

### ISSUE THREAD

**Issue by ghost** [naumch1k/one-fall#50]
### Description
After entering minimum eight lines into the input field 'Your message', the verical scrolling doesn't appear. Bit it is possible to see all entered text by swiping. 

### Environment
**Tablet:**
- Device: iPad (9th generation)
- OS: iPadOS 17.6.1
- Browser: Safari
- Version: 17.6.1

### Steps to reproduce:
1. Go to  https://develop--one-fall.netlify.app/
2. Scroll down to the footer of the site.
3. Enter eight lines into the **'Your message'** input field of the **'MESSAGE US'** form.

### Actual result:
The vertical scrolling is absent in the  'Your message' input field of the 'Message us' form after entering minimum eight lines into it.

### Expected result:
The vertical scrolling is displayed in the  'Your message' input field of the 'Message us' form after entering minimum eight lines into it.

### Attachments:
https://github.com/user-attachments/assets/f588099b-f61f-46a8-8f94-0c7b6cc5843b

### Additional context
This issue occurs in all browsers:
Google Chorme, version 128.0.6613.92;
Firefox, version 129.2 (44469).

**Comment by ghost** [comment]
@naumch1k It is not possible to resize the ‘Your message’ input field on the tablet. Maybe these issues are interconnected.
![IMG_0276](https://github.com/user-attachments/assets/7ab76ac0-affd-4555-832b-c0339d7ab16c)

**Comment by naumch1k** [comment]
I researched this issue, and it seems like iOS safari has dropped supporting custom CSS for scrollbars, as discussed [here](https://www.reddit.com/r/webdev/comments/lfi4ek/ios_14_safari_stopped_supporting_custom_css_for/) 😞 

According to [caniuse.com](https://caniuse.com/?search=%3A%3A-webkit-scrollbar) no `::-webkit-scrollbar` pseudo-elements are supported on any iOS browsers as they use the same version of WebKit. 

A work around I can think about is trying to implement a custom scrollbar for our text area element. I've noticed that [react-custom-scrollbars](https://www.npmjs.com/package/react-custom-scrollbars) is widely used and might be a suitable solution 🤓

@Yura33-dev, would you like to pick up this issue and give [react-custom-scrollbars](https://www.npmjs.com/package/react-custom-scrollbars) a try?

**Comment by Yura33-dev** [comment]
> I researched this issue, and it seems like iOS safari has dropped supporting custom CSS for scrollbars, as discussed [here](https://www.reddit.com/r/webdev/comments/lfi4ek/ios_14_safari_stopped_supporting_custom_css_for/) 😞
> 
> According to [caniuse.com](https://caniuse.com/?search=%3A%3A-webkit-scrollbar) no `::-webkit-scrollbar` pseudo-elements are supported on any iOS browsers as they use the same version of WebKit.
> 
> A work around I can think about is trying to implement a custom scrollbar for our text area element. I've noticed that [react-custom-scrollbars](https://www.npmjs.com/package/react-custom-scrollbars) is widely used and might be a suitable solution 🤓
> 
> @Yura33-dev, would you like to pick up this issue and give [react-custom-scrollbars](https://www.npmjs.com/package/react-custom-scrollbars) a try?

Yep, I will try 🙂

**Comment by Yura33-dev** [comment]
.take

**Comment by ghost** [comment]
@naumch1k Hey! I studied different sites on iPad that have the same text area fields. None of them have vertical scrolling.

**Comment by Yura33-dev** [comment]
@naumch1k Hello! I have checked textarea one more time and I have discovered that scrollbar actually exist on my mobile device. I don't know why it was absent when I checking it first time, but now it is alive in textarea.

So, my question is do I need to try to implement custom scrollbar with some 3rd-library or we leave as it is?

https://github.com/user-attachments/assets/8e5c9acb-ffc7-4d40-99b1-25d68673418d

**Comment by naumch1k** [comment]
@Yura33-dev Is scrollbar present on both of your iPhone devices?

**Comment by Yura33-dev** [comment]
> @Yura33-dev Is scrollbar present on both of your iPhone devices?

Yep, on both Iphone's (model XS and model 13)

**Comment by naumch1k** [comment]
@yuliia-harshyna @Yura33-dev 

So. it appears that the vertical scrollbar issue is present on both iPads and iPhones, though iPhones show some indication of scrolling. Given the effort required to implement a custom scrollbar and its limited impact on user experience, I suggest we leave it as it is.

I am marking it as wontfix for now. We have some other pressing things.

Thanks for your understanding!

**Comment by naumch1k** [comment]
Marking it as wontfix for now. We have some other pressing things.
